CLOUD_ID: 'oZdUnpEB0kun_0rS9iJj'
API_KEY: 'D2hJeZbYRJ2qd-w6U_9U5w'
OCR_DATA: 'D:\codePJ\AIC\FE\aic\BE\data\ocr'
ACR_DATA: 'D:\codePJ\AIC\FE\aic\BE\data\ocr'
OD_DATA: 'D:\codePJ\AIC\FE\aic\BE\data\ocr'
FRAMES_PATH: ''
OUTPUT_PATH: 'C:\Users\quang\Desktop\submission\'